- name: Build Docker Host
  hosts: container_docker_hosts
  tasks:
    - name: Ping hosts
      ansible.builtin.ping:
    - name: Print message
      ansible.builtin.debug:
        msg: Building of docker host is starting
    - name: Install necessary packages
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    - name: Add Docker GPG apt Key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu kinetic stable
        state: present
    - name: Update apt and install Docker
      ansible.builtin.apt:
        name: "{{ item }}"
        state: latest
        update_cache: true
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
    - name: Make sure Docker is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
    - name: Apt clean
      ansible.builtin.apt:
        clean: true
    - name: Apt autoremove
      ansible.builtin.apt:
        autoremove: true
